print("¡Hola!, ¡armemos una historia juntos! Ingresá los valores indicados en la consola y divertite creando una historia única." )

nombre = input("ingresá un nombre: ")
edad = input("ingresá una edad: ")
genero = input("ingresá un género literario: ")
nombre2 = input("ingresá otro nombre: ")
num = input("ingresá un número: ")
momento = input("ingresá un momento de tu vida: ")
lugar = input("ingresá un lugar: ")
bebida = input("Decime tu bebida favorita: ")
prenda = input("Decime tu prenda favorita: ")
genero_literario2 = input("Ingresá un género literario: ")
verbo = input("Ingresá una acción: ")

print("Hola, soy " + nombre + " y me gusta leer porque los libros me dan superpoderes. ")
print("Mi vida como superhéroe de la lectura comenzó cuando tenía " + edad + " años. ")
print("Recuerdo que uno de mis libros favoritos era sobre " + genero + ". ")
print("Creo que me lo regaló " + nombre2 + " y debo haberlo leído " + num + " veces. ")
print("Desde entonces me di cuenta que la lectura me daba superpoderes para hacer y viajar a donde quisiera. ")
print("Hoy en día, tengo el superpoder de elegir CUALQUIER libro que desee. ")
print("A veces escojo lecturas que me tranpsorten al pasado, a " + momento + " , o me lleven a visitar lugares en los que nunca antes he estado, como " + lugar + ". ")
print("Pero nada se compara con leer durante el verano, cuando puedo tomar mi " + bebida + " favorito, ponerme mi " + prenda + " favorito, y sentarme en  mi rincón especial para leer. ")
print("No sé ustedes, pero este verano me encantaría leer libros sobre " + genero_literario2 + ", ya que me dan deseos de " + verbo + ". ")
print("Esta es mi historia de como me convertí en un superhéroe de la lectura. ¿Cuál es la tuya?")